imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: ../../vendor/knplabs/doctrine-behaviors/config/orm-services.yml }
    - { resource: @IIMBlogBundle/Resources/config/admin.yml }
framework:
    #esi:             ~
    translator:      { fallback: fr }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'


# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

sensio_framework_extra:
    view: { annotations: false }

# Fos user config
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: IIM\BlogBundle\Entity\User



services:
  article.manager:
    class: IIM\BlogBundle\Manager\ArticleManager
    arguments:
    - "@doctrine.orm.entity_manager"
    -  IIM\BlogBundle\Entity\Article

  iim.article.form.type:
    class: IIM\BlogBundle\Form\ArticleType
    tags:
    - { name: form.type, alias: article}

  article.listener:
    class: IIM\BlogBundle\Listener\ArticleListener
    arguments: ["@service_container"]
    tags:
    - { name: doctrine.event_listener, event: prePersist }



sonata_doctrine_orm_admin:
  # default value is null, so doctrine uses the value defined in the configuration
  entity_manager: ~

  templates:
      form:
          - SonataDoctrineORMAdminBundle:Form:form_admin_fields.html.twig
      filter:
          - SonataDoctrineORMAdminBundle:Form:filter_admin_fields.html.twig
      types:
          list:
              array:      SonataAdminBundle:CRUD:list_array.html.twig
              boolean:    SonataAdminBundle:CRUD:list_boolean.html.twig
              date:       SonataAdminBundle:CRUD:list_date.html.twig
              time:       SonataAdminBundle:CRUD:list_time.html.twig
              datetime:   SonataAdminBundle:CRUD:list_datetime.html.twig
              text:       SonataAdminBundle:CRUD:base_list_field.html.twig
              trans:      SonataAdminBundle:CRUD:list_trans.html.twig
              string:     SonataAdminBundle:CRUD:base_list_field.html.twig
              smallint:   SonataAdminBundle:CRUD:base_list_field.html.twig
              bigint:     SonataAdminBundle:CRUD:base_list_field.html.twig
              integer:    SonataAdminBundle:CRUD:base_list_field.html.twig
              decimal:    SonataAdminBundle:CRUD:base_list_field.html.twig
              identifier: SonataAdminBundle:CRUD:base_list_field.html.twig

          show:
              array:      SonataAdminBundle:CRUD:show_array.html.twig
              boolean:    SonataAdminBundle:CRUD:show_boolean.html.twig
              date:       SonataAdminBundle:CRUD:show_date.html.twig
              time:       SonataAdminBundle:CRUD:show_time.html.twig
              datetime:   SonataAdminBundle:CRUD:show_datetime.html.twig
              text:       SonataAdminBundle:CRUD:base_show_field.html.twig
              trans:      SonataAdminBundle:CRUD:show_trans.html.twig
              string:     SonataAdminBundle:CRUD:base_show_field.html.twig
              smallint:   SonataAdminBundle:CRUD:base_show_field.html.twig
              bigint:     SonataAdminBundle:CRUD:base_show_field.html.twig
              integer:    SonataAdminBundle:CRUD:base_show_field.html.twig
              decimal:    SonataAdminBundle:CRUD:base_show_field.html.twig

sonata_block:
   default_contexts: [cms]
   blocks:
       sonata.admin.block.admin_list:
           contexts:   [admin]
       sonata.block.service.text:
       sonata.block.service.action:
       sonata.block.service.rss:

fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    disable_csrf_role: ROLE_API
    view:
        view_response_listener: 'force'
        formats:
            xml:  true
            json: true
    format_listener:
        rules:
            - { path: ^/, priorities: [ json, xml ], fallback_format: ~, prefer_extension: true }
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
    allowed_methods_listener: true
    access_denied_listener:
        json: true
    body_listener: true

# app/config/config.yml
nelmio_api_doc: ~

liip_cache_control:
    flash_message_listener: true
    authorization_listener: false
    rules:
        # the controls section values are used in a call to Response::setCache();
        - { path: ^/notes, method: [GET, HEAD], controls: { public: true, max_age: 15, s_maxage: 30, last_modified: "-1 hour" }, vary: [Accept-Encoding, Accept-Language] }


bazinga_rest_extra: ~

